name: Trolley Agent Deployment Action
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        required: true
        description: cluster_name to install the Agent on
        default: pavelzagalsky-gke-vkukhxio
      cluster_type:
        required: true
        description: cluster_type to install the Agent on
        default: gke
      mongo_user:
        required: true
        description: The Mongo DB User of the Trolley Service
        default: pavel
      mongo_password:
        required: true
        description: The Mongo DB Password of the Trolley Service
        default: pavel
      mongo_url:
        required: true
        description: The URL of the Mongo DB Server
        default: https://35a1-2a0d-6fc2-41e0-1500-45c-42d0-af98-3f1.eu.ngrok.io
      server_url:
        required: true
        description: The URL of the Trolley Server
        default: https://35a1-2a0d-6fc2-41e0-1500-45c-42d0-af98-3f1.eu.ngrok.io


jobs:
  trolley_agent_docker_deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDS_JSON }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: gcloud info
      - name: Setting up GKE Cloud
        run: |
          gcloud components install beta --quiet
          gcloud components install gke-gcloud-auth-plugin

      - name: Echo the values
        run: |
          echo "cluster_name is: ${{ github.event.inputs.cluster_name }}"
          echo "cluster_type is: ${{ github.event.inputs.cluster_type }}"
          echo "mongo_user is: ${{ github.event.inputs.mongo_user }}"
          echo "mongo_password is: ${{ github.event.inputs.mongo_password }}"
          echo "mongo_url are: ${{ github.event.inputs.mongo_url }}"
          echo "server_url is: ${{ github.event.inputs.server_url }}"
          
          CLUSTER_NAME="${{ github.event.inputs.cluster_name }}"
          echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_ENV
          CLUSTER_TYPE="${{ github.event.inputs.cluster_type }}"
          echo "CLUSTER_TYPE=${CLUSTER_TYPE}" >> $GITHUB_ENV
          MONGO_USER="${{ github.event.inputs.mongo_user }}"
          echo "MONGO_USER=${MONGO_USER}" >> $GITHUB_ENV
          MONGO_PASSWORD="${{ github.event.inputs.mongo_password }}"
          echo "MONGO_PASSWORD=${MONGO_PASSWORD}" >> $GITHUB_ENV
          MONGO_URL="${{ github.event.inputs.mongo_url }}"
          echo "MONGO_URL=${MONGO_URL}" >> $GITHUB_ENV
          SERVER_URL="${{ github.event.inputs.server_url }}"
          echo "SERVER_URL=${SERVER_URL}" >> $GITHUB_ENV

      - name: Prepare the YAML and deploy
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 deployment_utils/trolley_agent_deployment.py